name: bind_api
version: 0.2.1
description: A package to interact api.bind.com
homepage: https://bind.com/

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  dio: '^5.0.0'
  one_of: '>=1.5.0 <2.0.0'
  one_of_serializer: '>=1.5.0 <2.0.0'
  built_value: '>=8.4.0 <9.0.0'
  built_collection: '>=5.1.1 <6.0.0'
  build_runner: ^2.3.0

dev_dependencies:
  built_value_generator: '>=8.4.0 <9.0.0'
  test: ^1.16.0
